version: '3.7'


x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  fragmentation-producer:
    image: redpencil/fragmentation-producer:0.3.2
    environment:
      FOLDER_DEPTH: 1
      PAGE_RESOURCES_COUNT: 10
      LDES_STREAM_PREFIX: 'http://data.lblod.info/streams/lpdc/'
      TIME_TREE_RELATION_PATH: 'http://www.w3.org/ns/prov#generatedAtTime'
      CACHE_SIZE: 10
      DATA_FOLDER: '/data'
      ENABLE_AUTH: 'false'
    volumes:
      - './data/ldes-feed/:/data/'
